---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: ms-runner
  namespace: actions
spec:
  scaleTargetRef:
    name: ms-runners
  scaleDownDelaySecondsAfterScaleOut: 10
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - monsad/k8s-self-runner